### PR TITLE
Fixed: Urlparsing Encoding issues

### PR DESCRIPTION
**Pull request by frank-dspeed**
Plz never urlencode stuff your self that gets runned in a web browser it gets mixed up because the webbrowser it self does urlencode

Thanks greetings.

### CODE REVIEW

**Comment by frank-dspeed** [comment]
This is a improvment over pull request #232 wich is broken and buggy

**Comment by frank-dspeed** [comment]
@bago Importent Merge this in please so i can delete my fork this is not a optional patch its needed if you want to work with any RFC compilant backend.

**Comment by bago** [comment]
"RFC compliant backend"? There are no RFC for mosaico backends...

When you say "Plz never urlencode stuff your self that gets runned in a web browser it gets mixed up because the webbrowser it self does urlencode" I don't agree with this statement. Whenever you want to put content in an url paramenter YOU HAVE TO urlencode it, otherwise it will alter the way you deal with parameters... 

So, IMO you patch introduces bugs instead of fixing any...

If you don't think so please provide use cases/test cases and code that prove your point.

**Comment by bago** [comment]
Just try to upload a file having a "&", "space" or "+" and sequences like "%20" and "%2B" in its name after you applied your patch ... I know the current code works with weird filenames because we are using in productions and we manually tested for this cases..

**Comment by bago** [comment]
Please note that you get an "URL " and to find an "filename" from an url you have to "urldecode" it.
So
1) we urlencode it because you can't put an url in a parameter without encoding it.
2) you have to urldecode it in the backend if you want to find the path for that url.

Maybe the sample backend and others backends don't urldecode and this is a bug (feel free to open bugs/PR against the backends implementations).. but the urlencoding is required if you want to upload files with any name sequence.

**Comment by frank-dspeed** [comment]
@bago i integrated many external resources i am working for companys like apple encoding decoding don't happens at that point if you keep it that way your software is simply buggy example look into phpbackend connect it with your software look what happens.

**Comment by frank-dspeed** [comment]
@bago your production code simply works because you correct that error in your backend thats not the way to do it ! and i don't need to complain about that its simply a Importent information for your to make you as developer evolve i did last 5 weeks round about 14 mosaico deployments i should know more situations :+1: then running it one time in production with custom backend also many nodejs modules correct such errors that you did thats why you probally don't run into it.

**Comment by frank-dspeed** [comment]
and if you need a usecase no problem
```
# Get Root
sudo su -
# Install dev tools 
yum groupinstall -y 'Development Tools'
# Install NodeJS + ImageMagick + php5.4 + httpd
curl --silent --location https://rpm.nodesource.com/setup_7.x | bash -
yum install -y nodejs ImageMagick ImageMagick-devel php-devel php-pear httpd php
# php5.4 imagemagick integration
echo | pecl install imagick
echo "extension=imagick.so" > /etc/php.d/imagick.ini

# Install mosaico NodeJS Part
mkdir -p /srv
cd /srv
git clone https://github.com/voidlabs/mosaico
cd mosaico
npm install grunt@^1.0.0
npm install -g grunt-cli
npm install
rm -rf /var/www/html
grunt build && ln -s $PWD /var/www/html
# cd /var/www/html
curl -L https://raw.githubusercontent.com/direktspeed/mosaico-php-backend/master/backend-php/config.php > config.php
curl -L https://raw.githubusercontent.com/direktspeed/mosaico-php-backend/master/backend-php/index.php > index.php
curl -L https://raw.githubusercontent.com/direktspeed/mosaico-php-backend/master/backend-php/premailer.php > premailer.php
curl -L https://raw.githubusercontent.com/direktspeed/mosaico-php-backend/master/backend-php/.htaccess > .htaccess
mkdir -p uploads/thumbnails
chown apache:apache /srv/mosaico
chown -R apache:apache /srv/mosaico
chown apache:apache /var/www
#allow overide check if enabled should be     AllowOverride All
sed -i 's/AllowOverride None/AllowOverride All/g' /etc/httpd/conf/httpd.conf
sed -i 's/AllowOverride none/AllowOverride All/g' /etc/httpd/conf/httpd.conf
sed -i 's/enforcing/Permissive/g' /etc/sysconfig/selinux
setenforce Permissive
firewall-cmd --permanent --zone=public --add-port=80/tcp 
firewall-cmd --permanent --zone=public --add-port=443/tcp
firewall-cmd --reload
systemctl enable httpd && systemctl start httpd
echo "ALL DONE"
```
Edit the index.php file uncomment the line at top to die after request and show it and you will see what you get and hopefully aggree that this should look other :dagger:

**Comment by bago** [comment]
Believe me we did a lot of work on this.. 

Have you checked the "file name sequences" with weird chars in your "solution"? Otherwise deploy your "fixed" code somewhere and I will find an image filename that will be handled incorrectly.

**Comment by frank-dspeed** [comment]
@bago nothing will get handled incorrectly i feel realy sorry that you don't aggree with me and that you think that local double encoding client side is a good idea but ok we can close that as my code is working and your not i don't care its your project. Your free to belive in what ever you like hopyfully this pull request will  help some other users :D to find that bug faster when they try to work with any real servers and not nodejs directly :D.

**Comment by bago** [comment]
There is no "double encoding".. there is only one encoding to let you put an url as url parameter.
The other encoding is something related to url to file and file to url conversion and has nothing to do with the previous encoding.

**Comment by frank-dspeed** [comment]
@bago and whats with the browser ? current chrome for example will double encode that and will mix that up :) you simply did never cross browser tests because you don't got the money for a selenium deployment i think thats why your not trust me :) but its ok

**Comment by bago** [comment]
Please, let's not discuss about agree or disagree: it is just about testing some weird sequences... I don't remember the exact issue but please try uploading a filename with a name like "Me & You or Me %25%2B You or Me%20+%20.jpg" after you applied your patch and let me know. IMHO if you don't do "urlencoding" this won't work fine for you, but I will be happy to find I'm wrong (in that case I will search for my past tests that led us to introduce the encoding).

**Comment by bago** [comment]
Please don't assume I have to trust you if you don't trust me.

**Comment by bago** [comment]
As I said, I think there is a bug in the backends that do not urldecode that, but this can be fixed in the backend.. instead if you don't urlencode then the client will "loose" informations that the backend won't be able to fix.

**Comment by frank-dspeed** [comment]
@bago there is a bug in apache + php 7 :) and php 5 is what your suggesting not a bug in your code?

**Comment by frank-dspeed** [comment]
```
Array
(
    [REDIRECT_UNIQUE_ID] => WFp@DP@iGH4XnJ5xamvw1gAAAAA
    [REDIRECT_STATUS] => 200
    [UNIQUE_ID] => WFp@DP@iGH4XnJ5xamvw1gAAAAA
    [HTTP_HOST] => 172.17.0.4
    [HTTP_CONNECTION] => keep-alive
    [HTTP_CACHE_CONTROL] => max-age=0
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, sdch
    [HTTP_ACCEPT_LANGUAGE] => de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [SERVER_SIGNATURE] => 
    [SERVER_SOFTWARE] => Apache/2.4.6 (CentOS) PHP/5.4.16
    [SERVER_NAME] => 172.17.0.4
    [SERVER_ADDR] => 172.17.0.4
    [SERVER_PORT] => 80
    [REMOTE_ADDR] => 172.17.0.1
    [DOCUMENT_ROOT] => /var/www/html
    [REQUEST_SCHEME] => http
    [CONTEXT_PREFIX] => 
    [CONTEXT_DOCUMENT_ROOT] => /var/www/html
    [SERVER_ADMIN] => root@localhost
    [SCRIPT_FILENAME] => /var/www/html/index.php
    [REMOTE_PORT] => 34968
    [REDIRECT_QUERY_STRING] => method=placeholder¶ms=166%2C130
    [REDIRECT_URL] => /img/
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => method=placeholder¶ms=166%2C130
    [REQUEST_URI] => /img/?method=placeholder¶ms=166%2C130
    [SCRIPT_NAME] => /index.php
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1482325516.585
    [REQUEST_TIME] => 1482325516
)
```

**Comment by bago** [comment]
So, you are so genius that you don't even consider that I may have thought at this and done that for a reason.. in this case you can't help me. Bye Bye... 

If otherwise you want to be constructive and stop thinking you understand this thing completely and start trying to understand what I'm telling you then we can keep talking and find a way.

I won't go in depth any more unless you change your tone.

**Comment by bago** [comment]
I already explained the need to use encodeURIComponent on parameter values as per specifications.

Here I just want to add that I think your main issue is with URL and file paths.
the src parameter contains the URL of your image. 

An url for a path is created like this: 'http://yourhost/'+urlencode(yourfilepath)
So the local file path for a given url is created by urldecode(yoururlpath), so if you have to call a function with a "file path" and your input is a "file url" you have to do urldecoding on it. If instead you need the url then you use it as is.

So, let's say you have a local file named "path to + file %2b.png" then the url for this file will be something like "http://yoursite/youpath/path+to+%2B+file+%252b.png" ... if you use this url it will work in wget/curl/firefox/chrome while if you use the url "http://yoursite/youpath/path to + file %2b.png" it won't work in any of the 4 "browsers" (just try it).

Given that mosaico gives you the URL in the src parameter, if you want to manipulate the image you have to urldecode the url-path to find a correct local file path.

Now, maybe the sample node.js backend doesn't do this and the other opensource backends don't do that, but this is a bug in the backend code (not in apache, php, node, but in the backend code implementation) and we have to fix it.. but I still am pretty sure this is not a bug in the mosaico library way to build the url.

**Comment by frank-dspeed** [comment]
i don't think so because i simply corrected the frontend code and now all backend code works that did not work befor but interristing conclusion keep up the good work i refactor this project  anyway from knockout to CanJS we will see what gets more used and works better with less errors :)

**Comment by bago** [comment]
You are one of the most ignorant (missing of knowledge) person I found here.

Did you try uploading a file with "+" "&" and other special symbols in your "deployment"? In my deployment and with the current code against nodejs it works. In your code I bet it won't work.

I spent too much of my time trying to explain you something that every programmer should simply know.

You won't learn anything if you don't take in account there are people that know more than you.

You have been arrugant, I asked you to bring test cases, proofs of your "theory". I gave you a lot of stuff to work (special chars, look at the $_GET) and now, instead of simply saying "I'm sorry, i'm stupid, you was right" you keep yelling).

I will be very happy to test the canjs version of mosaico!

**Pull request closed without merging**
