### PR TITLE
adding the versafluid template

### PR DESCRIPTION
**Pull request by nabenzine**
Hey everyone, and thank you for you amazing work in mosaico,

Please add the versa-fluid template, it's the most responsive by far.

Cheers.

### CODE REVIEW

**Comment by bago** [comment]
Sorry but I think you don't have copyright/license to contribute/distribute this template.
The template author company didn't publish it for opensource: it can only be used on mosaico.io.

**Comment by nabenzine** [comment]
Hey baho, who is the template author company ? I can't find it anywhere ?

Thank you

**Comment by bago** [comment]
The author company is Void Labs (the same company that created Mosaico).
Void Labs has no plan to opensource that template, in the near term.

Please remove the code you submitted to github (also from your repository) as you don't have copyright/license for publishing it on github.

**Comment by nabenzine** [comment]
Thank you for you reply, I have already removed the repository, and by the way I found the template on github https://github.com/morloi/morloi.github.io/tree/master/templates

Cheers.

**Comment by bago** [comment]
Thank you for the link. That repository has been removed, too.

**Pull request closed without merging**
