### PR TITLE
Feature/tutorial

### PR DESCRIPTION
**Pull request by bwl21**
I have started to write a tutorial for the template language. In order to do this, I have forked your project, converted the repository to use gitflow and added a branch feature/tutorial.

you can see the tutorial here: https://github.com/bwl21/mosaico/blob/feature/tutorial/templates/tutorial/mosaico-tutorial.md

You might have a look into this, and give feedback if I am on the right track.

### CODE REVIEW

**Comment by mistaguy** [comment]
I like your tutorial, good start

**Comment by modist** [comment]
This is perfect - thnx :+1:

**Comment by modist** [comment]
just what the doctor ordered - big thnx !

**Comment by bago** [comment]
I had no chance, yet, to try it but it sounds it is very good! and it already satisfied 2 users so it must be great!

**Comment by bwl21** [comment]
ok, I will continue to work on this. Thanks

**Comment by bwl21** [comment]
@bago 

I have continued a bit with the tutorial
* added respect to "customize content". 
* added placeholders for further chapters
* marked some questions as "TODO"

As a Pity, with this minimalistic example, download does not work. The browser console throws:

```
Uncaught ReferenceError: Unable to process binding "bindIframe: function (){return $data }"
Message: Unable to process binding "template: function (){return /* special */(typeof templateMode !='undefined'&& templateMode =='wysiwyg') || false ?'anonymous-45750':'anonymous-13025' }"
Message: Unable to process binding "block: function (){return mainBlocks }"
Message: mainBlocks is not defined
```

I tried to find out in versafix-1 if there is adefinition for mainBlocks, but could not find it. Could you give a hint?

**Comment by bago** [comment]
mainBlocks is generated by data-ko-container="main".
At this time the editor expect you have one "data-ko-container" and its name is "main": in future I plan to add the ability to define multiple containers and to give them names, but at this time only "main" will work (and it is needed).

**Comment by bwl21** [comment]
I anticipated that. https://github.com/bwl21/mosaico/blob/feature/tutorial/templates/tutorial/template-tutorial.html#L31 contains  exactly one "data-ko-container" and its name is "main". But it still does not work.

**Comment by bago** [comment]
There is no ```<body>``` tag in the template.

**Comment by bago** [comment]
I just added #63

**Comment by bwl21** [comment]
Shame on me ... if I had run the checker provided by my IDE I would have found this.

Now the export works. Is it intended that  comments of "invisible" parts are exported?

```html
        <ul>
            <li>
                <div><p>item 1</p><p>aölkdjs f</p><p><br data-mce-bogus="1"></p></div>
            </li>
            <!-- ko if: (listsize() > 1) -->
            <!-- ko if: (listsize() > 2) -->
        </ul>
```

If not I'll open an issue.

**Comment by bago** [comment]
Sounds like a bug when the condition uses ">" (the cleaning regexp is ```content = content.replace(/<!-- ko [^>]* -->/g, '');```

Please, open an issue.

**Comment by bwl21** [comment]
I see i messed up something with the spec folder. I will fix that.

**Comment by bago** [comment]
Hi, the PR should only include the "tutorial" template and do nothing on existing files.

Expecially, the loading of the german strings or changes to editor.html does not belong to the tutorial feature.

**Pull request merged**
