### PR TITLE
Danish translation

### PR DESCRIPTION
**Pull request by tommyka**
New translation in danish

### CODE REVIEW

**Comment by bago** [comment]
Hi, thank you!

can you please submit them through POEditor?
https://github.com/voidlabs/mosaico/blob/master/res/lang/README.md
https://poeditor.com/join/project/nsFNi6zyOm

**Comment by tommyka** [comment]
I will look into it

**Comment by bago** [comment]
I added you as contributor to POEditor. You can find the "import" feature (up-arrow) to import the translations from your json file.

I'm sorry for this "double trip" but we prefer to have the "source" in POEditor and to give credits to the translators (if I do the import for you they credit me).

**Comment by bago** [comment]
Hi @tommyka: I authorized you to the project 2 weeks ago but I didn't see new actions... did you find blocking issues on poeditor?

**Comment by bago** [comment]
Hi @tommyka,

I can't apply this PR because Mosaico Translations are subject to CC-BY-4.0 license (Creative Commons - Attribution), while Mosaico itself is GPL, so I can't accept a simple PR. That's why I asked to put the translations on POEditor.

If you are not able to use POEditor but want to contribute the translations via this PR, please confirm me that you are fine with licensing your contribution under the CC-BY-4.0 license.

Otherwise please answer anyway so I'll close the PR without merging it.

**Pull request closed without merging**
